version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USER=database
      - DB_PASSWORD=mysecretpassword
      - DB_NAME=bannerdb
    depends_on:
      - db

  db:
    image: postgres:15.2
    restart: always
    ports:
      - 5435:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - DB_PASSWORD=mysecretpassword
      - DB_USER=database
      - DB_NAME=bannerdb
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: